language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'import JuliennedArrays, Pkg; Pkg.add("Coverage"); import Coverage.Codecov; JuliennedArrays |> pathof |> dirname |> Codecov.process_folder |> Codecov.submit'
  - julia -e 'import JuliennedArrays, Pkg; Pkg.add("Documenter"); joinpath(JuliennedArrays |> pathof |> dirname |> dirname, "docs", "make.jl") |> include'
