language: julia
os: linux
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: 1.0
jobs:
  include:
    - stage: "Documentation"
      julia: nightly
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/ docs/docs.jl
    - stage: "Coverage"
      julia: nightly
      os: linux
      script:
        - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=coverage/ coverage/coverage.jl
