name = "JuliennedArrays"
uuid = "5cadff95-7770-533d-a838-a1bf817ee6e0"
authors = ["Brandon Taylor <brandon.taylor221@gmail.com>"]

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"

[targets]
test = ["Documenter", "Coverage"]
