name = "JuliennedArrays"
uuid = "5cadff95-7770-533d-a838-a1bf817ee6e0"
repo = "https://github.com/bramtayl/JuliennedArrays.jl.git"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
